import React, { useState } from 'react';
import Box from '@mui/material/Box';
import HeroGrid from './HeroGrid';

function HeroGridContainer() {
  const heroNames = [
    'alchemist',
    'axe',
    'bristleback',
    'centaur',
    'chaos_knight',
    'dawnbreaker',
    'doom_bringer',
    'dragon_knight',
    'earth_spirit',
    'elder_titan',
    'huskar',
    'kunkka',
    'legion_commander',
    'life_stealer',
    'mars',
    'night_stalker',
    'ogre_magi',
    'omniknight',
    'primal_beast',
    'pudge',
    'slardar',
    'spirit_breaker',
    'sven',
    'tidehunter',
    'tiny',
    'treant',
    'tusk',
    'abyssal_underlord',
    'undying',
    'skeleton_king',
    'ancient_apparition',
    'crystal_maiden',
    'death_prophet',
    'disruptor',
    'enchantress',
    'grimstroke',
    'invoker',
    'jakiro',
    'keeper_of_the_light',
    'leshrac',
    'lich',
    'lina',
    'lion',
    'muerta',
    'furion',
    'necrolyte',
    'oracle',
    'obsidian_destroyer',
    'puck',
    'pugna',
    'queenofpain',
    'rubick',
    'shadow_demon',
    'shadow_shaman',
    'silencer',
    'skywrath_mage',
    'storm_spirit',
    'tinker',
    'warlock',
    'witch_doctor',
    'zuus',
    'antimage',
    'arc_warden',
    'bloodseeker',
    'bounty_hunter',
    'clinkz',
    'drow_ranger',
    'ember_spirit',
    'faceless_void',
    'gyrocopter',
    'hoodwink',
    'juggernaut',
    'luna',
    'medusa',
    'meepo',
    'monkey_king',
    'morphling',
    'naga_siren',
    'phantom_assassin',
    'phantom_lancer',
    'razor',
    'riki',
    'nevermore',
    'slark',
    'sniper',
    'spectre',
    'templar_assassin',
    'terrorblade',
    'troll_warlord',
    'ursa',
    'viper',
    'weaver',
    'abaddon',
    'bane',
    'batrider',
    'beastmaster',
    'brewmaster',
    'broodmother',
    'chen',
    'rattletrap',
    'gyrocopter',
    'dark_seer',
    'dark_willow',
    'dazzle',
    'enigma',
    'wisp',
    'lone_druid',
    'magnataur',
    'naga_siren',
    'marci',
    'mirana',
    'nyx_assassin',
    'pangolier',
    'phoenix',
    'sand_king',
    'snapfire',
    'techies',
    'shredder',
    'vengefulspirit',
    'venomancer',
    'visage',
    'void_spirit',
    'winter_wyvern',
  ];

  const heroPicData = heroesArr =>
    heroesArr.map(heroName => ({
      img: `https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${heroName}.png`,
      title: heroName,
      name: heroName,
    }));

  const heroData = heroPicData(heroNames);

  return (
    <div className='heroGrid'>
      <Box sx={{ height: '100%', width: '100%' }}>
        <HeroGrid heroData={heroData} />
      </Box>
    </div>
  );
}

export default HeroGridContainer;
